[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "YOUR_COOKIE_SECRET"
client_secret = "YOUR_CLIENT_SECRET"
client_id = "YOUR_CLIENT_ID"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"






