[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "fnwuen93w93w8bf78f9389b87987BUBVHV2178"
client_secret = "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"
client_id = "1049592230220-trh7ni7te5gd0lv40895j7gl68c5aot1.apps.googleusercontent.com"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"






